apiVersion: v1
kind: Pod
metadata:
  name: streamlit-app
  labels:
    app: streamlit-app
spec:
  containers:
  - name: stream-app-container
    image: streamlit-app:v1
    ports:
    - containerPort: 8501
